[package]
name = "solcery_ptr_account"
version = "0.1.0"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
solana-program = "=1.7.6"

[lib]
name = "solcery_ptr_account"
crate-type = ["cdylib", "lib"]
